FROM node:18.18.2
# Create app directory
WORKDIR /app
COPY package.json ./package.json
COPY package-lock.json ./package-lock.json
RUN npm install
COPY . .
EXPOSE 3000
ENV TASKS=20
CMD [ "node", "main.js"]

#etant dans le dossier planner :  docker build -t planner . -f DockerFile.planner

#image dans le port: docker run --network=mynetwork --name planner -p 3000:3000 -d planner
#execute : sh build.sh

