#Dockerfile for server1
FROM node:18.18.2
# Create app directory
WORKDIR /app
COPY package.json ./package.json
RUN npm install
COPY . .
EXPOSE 8080
CMD [ "node", "main.js"]


#etant dans le dossier worker : docker build -t worker . -f Dockerfile.worker

#image dans le port: docker run --network=mynetwork --name worker -p 8080:8080 -d worker

# docker run --network=mynetwork --name worker1 -e PORT=8070 -d worker
#execute : sh build.sh

# Dockerfile for Worker
